# Generated by Django 3.1 on 2020-09-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20200824_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
