# Generated by Django 3.1 on 2020-09-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('m', 'HOMBRE'), ('f', 'MUJER')], max_length=200, null=True),
        ),
    ]
