# Generated by Django 3.1 on 2020-09-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='tienda.Sizes'),
        ),
    ]
