# Generated by Django 3.1 on 2020-09-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_product_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sizes',
            new_name='SizesGeneral',
        ),
    ]
