# Generated by Django 3.1 on 2020-09-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_auto_20200906_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(null=True, to='tienda.SizesGeneral'),
        ),
    ]
