# Generated by Django 3.1 on 2020-09-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_auto_20200906_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.color'),
        ),
    ]
