# Generated by Django 3.1 on 2020-09-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_remove_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('red', 'red'), ('black', 'black')], max_length=200, null=True),
        ),
    ]
