# Generated by Django 3.1 on 2020-09-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='tienda.SizesGeneral'),
        ),
    ]
